let reponse={
    "code": 200,
    "errors": false,
    "data": {
      "id": 1611605184575,
      "type": "users",
      "attributes": [
        [
          {
            "BTC": [
              {
                "min_amount": "0.05",
                "name": "ETHBTC",
                "money_prec": 5,
                "stock": "ETH",
                "stock_prec": 6,
                "money": "BTC",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 2,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/eth.png"
              },
              {
                "min_amount": "0.15",
                "name": "LTCBTC",
                "money_prec": 6,
                "stock": "LTC",
                "stock_prec": 6,
                "money": "BTC",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 1,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/ltc.png"
              },
              {
                "min_amount": "0.2",
                "name": "DASHBTC",
                "money_prec": 5,
                "stock": "DASH",
                "stock_prec": 6,
                "money": "BTC",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 1,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/dash.png"
              },
              {
                "min_amount": "50",
                "name": "BDXBTC",
                "money_prec": 8,
                "stock": "BDX",
                "stock_prec": 3,
                "money": "BTC",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 3,
                "q": false,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/bdx.png"
              },
              {
                "min_amount": "20",
                "name": "TREEPBTC",
                "money_prec": 8,
                "stock": "TREEP",
                "stock_prec": 3,
                "money": "BTC",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 0,
                "q": false,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/treep.png"
              },
              {
                "min_amount": "10",
                "name": "BLURTBTC",
                "money_prec": 8,
                "stock": "BLURT",
                "stock_prec": 3,
                "money": "BTC",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 0,
                "q": false,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/blurt.png"
              }
            ]
          },
          {
            "USDT": [
              {
                "min_amount": "0.001",
                "name": "BTCUSDT",
                "money_prec": 2,
                "stock": "BTC",
                "stock_prec": 6,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": true,
                "priority": 2,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/btc.png"
              },
              {
                "min_amount": "50",
                "name": "BDXUSDT",
                "money_prec": 3,
                "stock": "BDX",
                "stock_prec": 3,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 3,
                "q": false,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/bdx.png"
              },
              {
                "min_amount": "0.05",
                "name": "ETHUSDT",
                "money_prec": 2,
                "stock": "ETH",
                "stock_prec": 6,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": true,
                "priority": 2,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/eth.png"
              },
              {
                "min_amount": "1.5",
                "name": "ZRXUSDT",
                "money_prec": 4,
                "stock": "ZRX",
                "stock_prec": 4,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 1,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/zrx.png"
              },
              {
                "min_amount": "100",
                "name": "PQTUSDT",
                "money_prec": 8,
                "stock": "PQT",
                "stock_prec": 3,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 0,
                "q": false,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/pqt.png"
              },
              {
                "min_amount": "50",
                "name": "TREEPUSDT",
                "money_prec": 8,
                "stock": "TREEP",
                "stock_prec": 3,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 0,
                "q": false,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/treep.png"
              },
              {
                "min_amount": "0.15",
                "name": "LINKUSDT",
                "money_prec": 3,
                "stock": "LINK",
                "stock_prec": 3,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 1,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/link.png"
              },
              {
                "min_amount": "5",
                "name": "BATUSDT",
                "money_prec": 4,
                "stock": "BAT",
                "stock_prec": 4,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 1,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/bat.png"
              },
              {
                "min_amount": "0.15",
                "name": "BANDUSDT",
                "money_prec": 2,
                "stock": "BAND",
                "stock_prec": 4,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 1,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/band.png"
              },
              {
                "min_amount": "0.002",
                "name": "COMPUSDT",
                "money_prec": 4,
                "stock": "COMP",
                "stock_prec": 3,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 1,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/comp.png"
              },
              {
                "min_amount": "5",
                "name": "LRCUSDT",
                "money_prec": 4,
                "stock": "LRC",
                "stock_prec": 3,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 1,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/lrc.png"
              },
              {
                "min_amount": "5",
                "name": "1INCHUSDT",
                "money_prec": 6,
                "stock": "1INCH",
                "stock_prec": 3,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 1,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/1inch.png"
              },
              {
                "min_amount": "10",
                "name": "GRTUSDT",
                "money_prec": 6,
                "stock": "GRT",
                "stock_prec": 4,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 1,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/grt.png"
              },
              {
                "min_amount": "5",
                "name": "SUSHIUSDT",
                "money_prec": 4,
                "stock": "SUSHI",
                "stock_prec": 3,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 1,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/sushi.png"
              },
              {
                "min_amount": "5",
                "name": "UNIUSDT",
                "money_prec": 5,
                "stock": "UNI",
                "stock_prec": 3,
                "money": "USDT",
                "fee_prec": 4,
                "is_favourite": false,
                "priority": 1,
                "q": true,
                "disable_trade": false,
                "logo_url": "https://storage.googleapis.com/beldex_images/coin/uni.png"
              }
            ]
          }
        ],
        [
          "ETHBTC",
          "LTCBTC",
          "DASHBTC",
          "BDXBTC",
          "BTCUSDT",
          "BDXUSDT",
          "ETHUSDT",
          "ZRXUSDT",
          "TREEPBTC",
          "PQTUSDT",
          "TREEPUSDT",
          "BLURTBTC",
          "LINKUSDT",
          "BATUSDT",
          "BANDUSDT",
          "COMPUSDT",
          "LRCUSDT",
          "1INCHUSDT",
          "GRTUSDT",
          "SUSHIUSDT",
          "UNIUSDT"
        ]
      ]
    }
  }